In [3]:
import numpy as np
np.array([1, 2])

array([1, 2])

In [5]:
import numpy as np
a =[1, 2]
b= [4, 5]
a = np.array(a)
b = np.array(b)
a/b

array([0.25, 0.4 ])

In [7]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int32


In [8]:
arr.shape

(4,)

In [10]:
arr.ndim

1

In [12]:
import numpy as np
arr = np.array([[1, 2, 3, 4]])
print(arr.dtype)
print(arr.ndim)
print(arr.shape)

int32
2
(1, 4)


In [13]:
import numpy as np
arr = np.array([[[1, 2, 3, 4]]])
print(arr.dtype)
print(arr.ndim)
print(arr.shape)

int32
3
(1, 1, 4)


In [18]:
import numpy as np
arr = np.array([[[1, 2, 3],[ 4, 5, 6],[7, 8, 9]]])
print(arr.ndim)


3


In [20]:
print(arr.shape)

(1, 3, 3)


In [23]:
import numpy as np
a = np.array([1,2,3,4,5])
np.savetxt('out.txt', a)
b = np.loadtxt('out.txt')
print(b)

[1. 2. 3. 4. 5.]


In [22]:
import numpy as np
a = np.array([1,2,3,4,5])

np.savetxt('out.txt',a)

b = np.loadtxt('out.txt')

print(b)

[1. 2. 3. 4. 5.]


In [24]:
import numpy as np
arr = np.arange(12)
arr.shape

(12,)

In [26]:
import numpy as np
arr=np.arange(12)

arr1=arr.reshape(3,4)

print("Array arr1:\n",arr1)

print("Element at eth row and eth column of arr1 is:",arr1[0,0])

print("Element at 1st row and 2nd column of arr1 is:", arr1[1,2])

Array arr1:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Element at eth row and eth column of arr1 is: 0
Element at 1st row and 2nd column of arr1 is: 6


In [27]:
import numpy as np
arr = np.arange(6)
print("array arr:",arr)
print("sliced element of array: ", arr[1:5])

array arr: [0 1 2 3 4 5]
sliced element of array:  [1 2 3 4]


In [28]:
a = np.mean([1,2,3,4,5])
a

3.0

In [32]:
a = np.median([1,2,3,4,5])
a

3.0

In [33]:
a = np.std([1,2,3,4,5])
a

1.4142135623730951

In [34]:
a = np.ptp([1,2,3,4,5])
a

4

In [37]:
np.zeros((10,4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [38]:
a = np.var([1,2,3,4,5])
a

2.0